apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memos-db
  namespace: memos
spec:
  selector:
    matchLabels:
     
              value: secretmemos
            - name: POSTGRES_DB
              value: memosdb
  volumeClaimTemplates:
    - metadata:
        name: lh-db-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 2Gi
